apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-{{ include "OpenMetadata.fullname" . }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hpa-{{ include "OpenMetadata.fullname"  . }}
 minReplicas: {{ .Values.hpa.minReplicas }}
 maxReplicas: {{ .Values.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage}}